import { SupportedLanguage, LanguageOption } from '../types/enterprise';

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇬🇧' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' },
  { code: 'hinglish', name: 'Hinglish', nativeName: 'Hinglish (Colloquial)', flag: '🇮🇳' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', flag: '🇩🇪' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', flag: '🇸🇦' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', flag: '🇮🇳' },
];

export const TRANSLATIONS: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    dashboard: 'Dashboard',
    digital_twin: 'School Digital Twin',
    ai_copilot: 'AI School Copilot',
    student_risk: 'Risk Prediction',
    parent_engagement: 'Parent Engagement',
    growth_timeline: 'Growth Timeline',
    career_guidance: 'Career Guidance',
    face_attendance: 'Face Recognition Attendance',
    gamification: 'Student Gamification',
    ai_worksheet_generator: 'AI Worksheet Generator',
    executive_command: 'Executive Command Center',
    workflow_builder: 'Workflow Builder',
    automation_engine: 'Automation Engine',
    kpi_analytics: 'KPI Analytics',
    saas_tenants: 'Multi-Campus Tenants',
    students: 'Students Directory',
    attendance: 'Attendance',
    fees: 'Fees & Invoicing',
    transport: 'Smart Transport',
    library: 'Library',
    payroll: 'Payroll',
    exams: 'Examinations',
    search_placeholder: 'Search anything (Ctrl+K)...',
    health_score: 'School Health Score',
    active_students: 'Active Students',
    attendance_rate: 'Attendance Rate',
    total_revenue: 'Total Revenue',
    risk_critical: 'Critical Risk',
    active_bus: 'Live Fleet Tracking',
    system_status: 'Zero-Trust Enforcement Active',
    language: 'Language',
    tenant: 'Campus Tenant',
  },
  hi: {
    dashboard: 'डैशबोर्ड',
    digital_twin: 'डिजिटल ट्विन कैंपस',
    ai_copilot: 'एआई स्कूल कोपायलट',
    student_risk: 'छात्र जोखिम भविष्यवाणी',
    parent_engagement: 'अभिभावक सहभागिता',
    growth_timeline: 'छात्र विकास यात्रा',
    career_guidance: 'करियर मार्गदर्शन केंद्र',
    face_attendance: 'चेहरा पहचान उपस्थिति',
    gamification: 'छात्र गेमिफिकेशन व अंक',
    ai_worksheet_generator: 'एआई कार्यपत्रक जनरेटर',
    executive_command: 'कार्यकारी कमांड सेंटर',
    workflow_builder: 'वर्कफ़्लो अनुमोदन निर्माता',
    automation_engine: 'स्वचालन नियम इंजन',
    kpi_analytics: 'केपीआई एनालिटिक्स',
    saas_tenants: 'बहु-परिसर संस्थान',
    students: 'छात्र निर्देशिका',
    attendance: 'दैनिक उपस्थिति',
    fees: 'शुल्क व चालान',
    transport: 'स्मार्ट वाहन बेड़ा',
    library: 'पुस्तकालय',
    payroll: 'वेतन प्रबंधन',
    exams: 'परीक्षा व अंक',
    search_placeholder: 'खोजें (Ctrl+K)...',
    health_score: 'विद्यालय स्वास्थ्य स्कोर',
    active_students: 'सक्रिय छात्र',
    attendance_rate: 'उपस्थिति दर',
    total_revenue: 'कुल संग्रह',
    risk_critical: 'गंभीर जोखिम',
    active_bus: 'लाइव बस ट्रैकिंग',
    system_status: 'ज़ीरो-ट्रस्ट सुरक्षा सक्रिय',
    language: 'भाषा',
    tenant: 'परिसर',
  },
  hinglish: {
    dashboard: 'Dashboard Overview',
    digital_twin: 'Campus Digital Twin',
    ai_copilot: 'Smart AI Copilot',
    student_risk: 'Student Risk Engine',
    parent_engagement: 'Parent Engagement Score',
    growth_timeline: 'Student Growth Journey',
    career_guidance: 'Career Guidance Hub',
    face_attendance: 'Face Recognition Haziri',
    gamification: 'Points & Badges System',
    ai_worksheet_generator: 'AI Worksheet Maker',
    executive_command: 'Principal Command Center',
    workflow_builder: 'Approval Workflow Builder',
    automation_engine: 'IF-THEN Automation Rules',
    kpi_analytics: 'School KPI Analytics',
    saas_tenants: 'Multi-Branch Campuses',
    students: 'Students Directory',
    attendance: 'Daily Attendance',
    fees: 'Fees & Invoices',
    transport: 'School Bus Fleet GPS',
    library: 'Digital Library',
    payroll: 'Staff Salary & Payroll',
    exams: 'Exams & Results',
    search_placeholder: 'Kuch bhi search karein (Ctrl+K)...',
    health_score: 'School Health Score',
    active_students: 'Kul Enrolled Students',
    attendance_rate: 'Attendance Average',
    total_revenue: 'Fees Collection Total',
    risk_critical: 'High Alert Students',
    active_bus: 'Buses Live Location',
    system_status: 'Zero-Trust Fully Protected',
    language: 'Bhasha',
    tenant: 'Active Campus',
  },
  es: {
    dashboard: 'Panel Principal',
    digital_twin: 'Gemelo Digital del Colegio',
    ai_copilot: 'Copiloto Escolar IA',
    student_risk: 'Predicción de Riesgo',
    parent_engagement: 'Compromiso Parental',
    growth_timeline: 'Trayectoria del Alumno',
    career_guidance: 'Orientación Vocacional',
    face_attendance: 'Asistencia Facial',
    gamification: 'Gamificación y Puntos',
    ai_worksheet_generator: 'Generador IA de Tareas',
    executive_command: 'Centro de Comando Ejecutivo',
    workflow_builder: 'Gestor de Flujos de Aprobación',
    automation_engine: 'Motor de Automatización',
    kpi_analytics: 'Analítica de KPIs',
    saas_tenants: 'Instituciones Multi-Campus',
    students: 'Directorio de Alumnos',
    attendance: 'Asistencia',
    fees: 'Tasas y Facturación',
    transport: 'Transporte Inteligente',
    library: 'Biblioteca',
    payroll: 'Nóminas',
    exams: 'Exámenes y Calificaciones',
    search_placeholder: 'Buscar cualquier cosa (Ctrl+K)...',
    health_score: 'Puntuación de Salud Escolar',
    active_students: 'Alumnos Activos',
    attendance_rate: 'Tasa de Asistencia',
    total_revenue: 'Ingresos Totales',
    risk_critical: 'Riesgo Crítico',
    active_bus: 'Flota en Vivo',
    system_status: 'Zero-Trust Activo',
    language: 'Idioma',
    tenant: 'Campus Activo',
  },
  fr: {
    dashboard: 'Tableau de Bord',
    digital_twin: 'Jumeau Numérique de l’École',
    ai_copilot: 'Copilote IA Scolaire',
    student_risk: 'Prédiction du Risque',
    parent_engagement: 'Engagement des Parents',
    growth_timeline: 'Parcours de l’Élève',
    career_guidance: 'Orientation Professionnelle',
    face_attendance: 'Présence par Reconnaissance Faciale',
    gamification: 'Gamification et Récompenses',
    ai_worksheet_generator: 'Générateur de Fiches IA',
    executive_command: 'Centre de Commandement Direction',
    workflow_builder: 'Créateur de Flux de Travail',
    automation_engine: 'Moteur d’Automatisation',
    kpi_analytics: 'Analytique KPI',
    saas_tenants: 'Multi-Campus Établissements',
    students: 'Répertoire des Élèves',
    attendance: 'Présence',
    fees: 'Frais et Factures',
    transport: 'Flotte de Transport',
    library: 'Bibliothèque',
    payroll: 'Salaires et Paie',
    exams: 'Examens et Notes',
    search_placeholder: 'Rechercher (Ctrl+K)...',
    health_score: 'Score de Santé de l’École',
    active_students: 'Élèves Inscrits',
    attendance_rate: 'Taux de Présence',
    total_revenue: 'Recettes Totales',
    risk_critical: 'Risque Critique',
    active_bus: 'Flotte en Temps Réel',
    system_status: 'Sécurité Zero-Trust Active',
    language: 'Langue',
    tenant: 'Campus Actif',
  },
  de: {
    dashboard: 'Übersicht',
    digital_twin: 'Digitaler Schulzwilling',
    ai_copilot: 'KI-Schul-Copilot',
    student_risk: 'Schülerrisiko-Vorhersage',
    parent_engagement: 'Elternbeteiligung',
    growth_timeline: 'Schüler-Entwicklungsverlauf',
    career_guidance: 'Berufsberatung',
    face_attendance: 'Gesichtserkennung Anwesenheit',
    gamification: 'Gamification & Punkte',
    ai_worksheet_generator: 'KI-Arbeitsblatt-Generator',
    executive_command: 'Führungskommando-Zentrale',
    workflow_builder: 'Workflow-Genehmigungs-Designer',
    automation_engine: 'Automatisierungs-Engine',
    kpi_analytics: 'KPI-Analysen',
    saas_tenants: 'Multi-Campus Mandanten',
    students: 'Schülerverzeichnis',
    attendance: 'Anwesenheit',
    fees: 'Gebühren & Rechnungen',
    transport: 'Transport-Flotte',
    library: 'Bibliothek',
    payroll: 'Gehaltsabrechnung',
    exams: 'Prüfungen & Noten',
    search_placeholder: 'Suchen (Ctrl+K)...',
    health_score: 'Schul-Gesundheitswert',
    active_students: 'Aktive Schüler',
    attendance_rate: 'Anwesenheitsquote',
    total_revenue: 'Gesamteinnahmen',
    risk_critical: 'Kritisches Risiko',
    active_bus: 'Echtzeit-Flotte',
    system_status: 'Zero-Trust Aktiv',
    language: 'Sprache',
    tenant: 'Campus',
  },
  ar: {
    dashboard: 'لوحة القيادة',
    digital_twin: 'التوأم الرقمي للحرم المدرسي',
    ai_copilot: 'المساعد الذكي للمدرسة',
    student_risk: 'محرك التنبؤ بالمخاطر',
    parent_engagement: 'تفاعل أولياء الأمور',
    growth_timeline: 'مسيرة نمو الطالب',
    career_guidance: 'مركز التوجيه المهني',
    face_attendance: 'حضور بالتعرف على الوجه',
    gamification: 'نقاط وتحديات الطلاب',
    ai_worksheet_generator: 'مُولّد أوراق العمل بالذكاء الاصطناعي',
    executive_command: 'مركز القيادة التنفيذية',
    workflow_builder: 'باني سير العمل والموافقات',
    automation_engine: 'محرك الأتمتة الذكي',
    kpi_analytics: 'تحليلات مؤشرات الأداء',
    saas_tenants: 'فروع ومؤسسات متعددة',
    students: 'دليل الطلاب',
    attendance: 'الحضور اليومي',
    fees: 'الرسوم والفواتير',
    transport: 'أسطول النقل المدرسي',
    library: 'المكتبة المدرسية',
    payroll: 'رواتب الموظفين',
    exams: 'الامتحانات والنتائج',
    search_placeholder: 'بحث في كل شيء (Ctrl+K)...',
    health_score: 'مؤشر صحة المدرسة',
    active_students: 'الطلاب المسجلون',
    attendance_rate: 'معدل الحضور',
    total_revenue: 'إجمالي الإيرادات',
    risk_critical: 'خطر حرج',
    active_bus: 'تتبع الحافلات المباشر',
    system_status: 'نظام حماية منعدم الثقة فعّال',
    language: 'اللغة',
    tenant: 'الفرع المدرسي',
  },
  ta: {
    dashboard: 'முகப்பு பலகை',
    digital_twin: 'டிஜிட்டல் இரட்டை வளாகம்',
    ai_copilot: 'ஏஐ பள்ளி வழிகாட்டி',
    student_risk: 'மாணவர் இடர் கணிப்பு',
    parent_engagement: 'பெற்றோர் ஈடுபாடு',
    growth_timeline: 'மாணவர் வளர்ச்சிப் பாதை',
    career_guidance: 'தொழில் வழிகாட்டுதல் மையம்',
    face_attendance: 'முக அங்கீகார வருகைப் பதிவு',
    gamification: 'மாணவர் புள்ளிகள் மற்றும் பதக்கங்கள்',
    ai_worksheet_generator: 'ஏஐ பயிற்சித்தாள் உருவாக்கி',
    executive_command: 'முதன்மை கட்டுப்பாட்டு மையம்',
    workflow_builder: 'பணிப்பாய்வு ஒப்புதல் மையம்',
    automation_engine: 'தானியங்கி விதி இயந்திரம்',
    kpi_analytics: 'பள்ளி அளவீடுகள்',
    saas_tenants: 'பல வளாக நிறுவனங்கள்',
    students: 'மாணவர் பட்டியல்',
    attendance: 'வருகைப்பதிவு',
    fees: 'கட்டணம் மற்றும் ரசீது',
    transport: 'பேருந்து போக்குவரத்து',
    library: 'நூலகம்',
    payroll: 'ஊதிய மேலாண்மை',
    exams: 'தேர்வுகள் மற்றும் மதிப்பெண்கள்',
    search_placeholder: 'தேடவும் (Ctrl+K)...',
    health_score: 'பள்ளி நலம் மதிப்பீடு',
    active_students: 'செயலில் உள்ள மாணவர்கள்',
    attendance_rate: 'வருகை விகிதம்',
    total_revenue: 'மொத்த வசூல்',
    risk_critical: 'அவசர கவனம் தேவை',
    active_bus: 'பேருந்து நேரலை கண்காணிப்பு',
    system_status: 'பூஜ்ஜிய-நம்பிக்கை பாதுகாப்பு செயல்படுகிறது',
    language: 'மொழி',
    tenant: 'வளாகம்',
  },
};

export const translateText = (key: string, lang: SupportedLanguage = 'en'): string => {
  return TRANSLATIONS[lang]?.[key] || TRANSLATIONS.en[key] || key;
};
